channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.2.1
- pip:
  - mlflow==2.8.0
  - cffi==1.16.0
  - cloudpickle==2.2.1
  - defusedxml==0.7.1
  - einops==0.7.0
  - ipython==8.16.1
  - matplotlib==3.8.0
  - numpy==1.26.0
  - packaging==23.2
  - pandas==2.1.1
  - pytorch-lightning==2.1.1
  - pyyaml==6.0.1
  - requests==2.31.0
  - scipy==1.11.3
  - seisbench==0.5.3
  - torch==2.1.0
  - torchaudio==2.1.0
  - torchvision==0.16.0
name: mlflow-env
